### ISSUE TITLE
No default value for variables when using env vars

### ISSUE THREAD

**Issue by Zweer** [tusharmath/node-config-ts#29]
Hi,

I've found no way to use a default value when I want to link a config var to an environment var.
In node-config you have a different file where you set the variables, while here, using the same file that is much easier (!!!), I cannot specify the default value.

For example I want to specify the default port (3000) to use in the local environment, while it should use the port in the "PORT" env var when deployed...

Any idea?

Thanks

**Comment by tusharmath** [comment]
Can you try something like this —

**default.json**
```json
{
  "port": 3000
}
```

**env/production.json**
```json
{
  "port": "@@PORT"
}
```

What this setup means is that the default port value is going to be `3000` but it can be overridden if needed in production. Similarly if you would like to override the `port` in development also you could create another file like this — 

**env/development.json**
```json
{
  "port": "@@PORT"
}
```

Let me know if this works :)

**Comment by Zweer** [comment]
Hey,

thanks for the insight, but my use-case is a little different: I want to
always use the @@port syntax, except during local development when I want
to fallback to the default "3000" (or better, I'm lazy and i don't want to
specify the env var =)

BTW thanks for the patience...

**Comment by tusharmath** [comment]
How does you application know that it being run in "local" vs any other env? In `node-config-ts` the convention is that you only have two "env" viz — `development` and `production`. You could specify this using `NODE_ENV` env variable.

If I understood your problem correctly then my recommended solution should work. I would like to understand which part wouldn't work for your use case?

**Comment by Zweer** [comment]
Hi,

right now my use case is:
- local development: no env vars (lazy boy)
- remote server, dev env: NODE_ENV=development + PORT env vars
- remote server, staging env: NODE_ENV=staging + PORT env vars
- remote server, prod env: NODE_ENV=production + PORT env vars

as you can see I always have the "PORT" env var set (my "remote server" is heroku, so they specify it for you), but in local development where I start the server with a simple "nodemon"...

as you can see my only concern is to continue being lazy =)

**Comment by tusharmath** [comment]
Here is what I would then propose — 

Actually `NODE_ENV` shouldn't be mixed with the `DEPLOYMENT` variable.  You should only have a development env or a production env. Modules such as expressjs can behave differently based on what `NODE_ENV` is set to. So here is what you could do instead — 

- local development: no env vars (lazy boy) *automatically load from default.json*
- remote server, dev env: NODE_ENV=production +  *DEPLOYMENT=development* + PORT env vars
- remote server, staging env: NODE_ENV=production + *DEPLOYMENT=staging* + PORT env vars
- remote server, prod env: NODE_ENV=production + *DEPLOYMENT=production* + PORT env vars

As you can see except in your local env, everywhere the NODE_ENV is set to production. This is generally a good practice since a lot of npm modules perform better when the NODE_ENV is set to production.

**Comment by Zweer** [comment]
Mmm I see your point... yes, you are right, trying to make things different
is better!!!

Thanks a lot, first of all for the patience!!!

Cya
