### ISSUE TITLE
Type errors

### ISSUE THREAD

**Issue by agorina** [tusharmath/node-config-ts#63]
If the configuration is defined with the env. variables (` "port": "@@PORT"`), the resulting data type is **undefined**.

If/when I have the env. variable in one `DEPLOYMENT` and a real value in another, the resulting configuration has different data types. This leads to various issues during deployment. 

Please advise.

P.S.: While I was learning how to use this module (which I like), I have posted a few questions and did not get any responses here. Is this package being supported? Due to the lack of responses AND the above issue, I am considering switching to an alternative package. Really hope to get the answer here. Thank you.

**Comment by tusharmath** [comment]
Hi Agorina, apologies for the late response, have been really swamped at work. I do open source only in my free time and lately, I haven't been able to get time to respond to issues. Really sorry about that!


The type info is generated based on what information is available at compile time. If you think about it, `port` isn't guaranteed to be available because ENV variables are typically optionally passed.

**Comment by agorina** [comment]
Thank you very much for answering, and not need to apologize. Your response makes sense.

**Comment by divideby0** [comment]
Thanks for the great work on this library @tusharmath. I love the concept of your library but this one issue is preventing me from using it more pervasively and I was literally just about to report the same challenge. From my perspective, the problem with `undefined` is that *is* a type, but a falsy type that indicates that something hasn't been initialized. For example, this block is illegal in TypeScript:

```typescript
// Error: Type '"foo"' is not assignable to type 'undefined'
const value: undefined = "foo";
```

Instead if we set the type to something like `undefined | string` or `any` or `unknown`, this would force our code to handle cases where the value is null but also read it as a string (which can be parsed to other types) if it is defined.

Another possible way to address this issue might be the [node-config way](https://github.com/lorenwest/node-config/wiki/Environment-Variables#custom-environment-variables) where they have a separate JSON file specifically for envvar overlay. Personally, I've always found their `custom-environment-variables.json` filename to be a bit long. But maybe we could have something like `envvars.json`. If you keep `default.json` but add `envvars.json` to the `loadFileConfigs` function, that would allow users to specify something like:

```json
// default.json
{
  "foo_flag": true
}

// envvars.json
{
  "foo_flag": "@@FOO_FLAG"
}
```

And the type generator would know to treat `foo_flag` as `boolean`.

I'd be curious to know if either of these are viable and in-line with your design vision @tusharmath . @agorina i'd also be curious if something like any of these would be helpful for your use cases.

**Comment by agorina** [comment]
@divideby0, your suggestions above are similar to what I was considering.

**Comment by tusharmath** [comment]
@divideby0 I think one problem that most consumers of the library face is that they try to use env variables in `default.json`.

`default.json` as the name suggests, should contain default values always, that makes it easier to infer the type.
Using env variables in default.json makes it impossible to infer the type-info from the config. For eg: 

```json
{
  "port": "@@PORT"
}
```
The correct inference for `port` should be `number` but because it's read from an env variable it hard for node-config-ts to determine it's expected type.

You are right it could be `string | undefined` as a default @agorina and I can make a fix for it so that it's a little less confusing :)

**Comment by agorina** [comment]
The change mentioned above will be helpful. Thank you very much for addressing it!

**Comment by divideby0** [comment]
Thank you as well. I agree that embedding envvars in `default.json` is a little bit awkward. But the alternative would be to include the same envvar references in every environment (e.g. `development.json`, `production.json`). I'd considered that, but had concerns that it potentially lead to unexpected configuration drift if you're following 12-factor but accidentally change your envvar references in one place and not all the others.
